# 
# Sets up DB for application
# @author E. M. Maximilien
# Copyright (C) IBM Corp., 2011
# License under the MIT license, found here: http://goo.gl/s9uhf
#

development:
  adapter: mysql
  database: people_finder_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  database: people_finder_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: people_finder_production
  username: root
  password:
  socket: /tmp/mysql.sock

