development:
  api_key: 8090a7f445674bafcd40039ad728a4a5
  secret_key: c359dd3e8edae7194767c59b79e32309
  canvas_page_name: haiti_survivors
  callback_url: http://174.129.134.98:5000/
  tunnel:
    public_host_username: tunnlr47
    public_host: ssh1.tunnlr.com
    public_port: 10141
    local_port: 4000

test:
  api_key: 8090a7f445674bafcd40039ad728a4a5
  secret_key: c359dd3e8edae7194767c59b79e32309
  canvas_page_name: haiti_survivors
  callback_url: http://174.129.134.98:5000/
  tunnel:
    public_host_username: tunnlr47
    public_host: ssh1.tunnlr.com
    public_port: 10141
    local_port: 4000

production:
  api_key: 8090a7f445674bafcd40039ad728a4a5
  secret_key: c359dd3e8edae7194767c59b79e32309
  canvas_page_name: haiti_survivors
  callback_url: http://174.129.134.98:5000/
  tunnel:
    public_host_username: tunnlr47
    public_host: ssh1.tunnlr.com
    public_port: 10141
    local_port: 4000
