# 
# Sets Facebooker for application (Development)
# @author E. M. Maximilien
# Copyright (C) IBM Corp., 2011
# License under the MIT license, found here: http://goo.gl/s9uhf
#

development:
  api_key: XXXX
  secret_key: XXX
  canvas_page_name: japan_pf_dev
  callback_url: http://web1.tunnlr.com:10141/
  tunnel:
    public_host_username: tunnlr47
    public_host: ssh1.tunnlr.com
    public_port: 10141
    local_port: 4000

test:
  api_key: XXXX
  secret_key: XXXX
  canvas_page_name: japan_pf_dev
  callback_url: http://web1.tunnlr.com:10141/
  tunnel:
    public_host_username: tunnlr47
    public_host: ssh1.tunnlr.com
    public_port: 10141
    local_port: 4000

production:
  api_key: XXXX
  secret_key: XXXX
  canvas_page_name: japan_pf_dev
  callback_url: http://web1.tunnlr.com:10141/
  tunnel:
    public_host_username: tunnlr47
    public_host: ssh1.tunnlr.com
    public_port: 10141
    local_port: 4000
