# 
# Collects all credential information in one place.
# Typically this file is not checked in with data but updated when deployed.
# @author E. M. Maximilien
# Copyright (C) IBM Corp., 2011
# License under the MIT license, found here: http://goo.gl/s9uhf
#

development:
  google_db:
    auth_key: XXXX
  google_maps:
    api_key: XXXX
  twitter:
    username: haiti_survivors
    password: XXXX
    consumer_key: XXXX
    consumer_secret: XXXX
  bitly:
    login: haiti_survivors
    api_key: XXXX

test:
  google_db:
    auth_key: XXXX
  google_maps:
    api_key: XXXX
  twitter:
    username: haiti_survivors
    password: XXXX
    consumer_key: XXXX
    consumer_secret: XXXX
  bitly:
    login: haiti_survivors
    api_key: XXXX
      
production:
  google_db:
    auth_key: XXXX
  google_maps:
    api_key: XXXX
  twitter:
    username: haiti_survivors
    password: XXXX
    consumer_key: XXXX
    consumer_secret: XXXX
  bitly:
    login: haiti_survivors
    api_key: XXXX